name: Deploy
on: push
jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    name: Upload
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get lftp
        run: sudo apt install lftp
      - name: Upload File
        run: lftp -c "open -p 21 -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOSTNAME }}; put README.md"
      - name: Mirror Directory
        run: lftp -c "open -p 21 -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOSTNAME }}; mirror -v -R ./ffmpeg /ffmpeg"
