name: 🚀 FTP Deploy
on: [push, workflow_dispatch]
jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2

      - name: 📦 Get lftp
        run: sudo apt install lftp

      - name: 📄 Upload File
        run: lftp -e "set ftp:verify-certificate no; put -O /destination/ ./README.md" -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOSTNAME }}

      - name: 📁 Upload Folder
        run: lftp -e "set ftp:verify-certificate no; mirror --parallel=100 -R ./ffmpeg/ /ffmpeg/" -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOSTNAME }}